export const notionHome = 'https://app.notion.com/p/3d2b7a683ee780978d25c7036df98238?source=copy_link'
export const blenderHome = 'https://app.notion.com/p/Blender-3d2b7a683ee78001a2f0d5b0b83b9302?pvs=25'

export const platforms = [
  { id: 'all', label: '全部内容', english: 'ALL NOTES', short: 'ALL', tone: 'gold' },
  { id: 'ae', label: 'After Effects', english: 'AE ECOSYSTEM', short: 'AE', tone: 'gold' },
  { id: 'blender', label: 'Blender', english: 'GEOMETRY NODES', short: 'BLENDER', tone: 'violet' },
]

const item = (title, note, tags = [], images = []) => ({ title, note, tags, images })

export const categories = [
  {
    id: 'bcc',
    platform: 'ae',
    label: 'BCC 系列',
    english: 'BORIS CONTINUUM',
    short: 'BCC',
    tone: 'gold',
    source: 'https://app.notion.com/p/AE-BCC-3d2b7a683ee7807cac7aeb50f2aabb9f?pvs=25',
    entries: [
      item('BCC+ Borders', '给画面添加可控边界和画框。', ['风格化', '边界']),
      item('BCC+ Color Shadow', '阈值与梯度渐变组合，用于生成彩色阴影。', ['风格化', '颜色']),
      item('BCC+ Infrared', '比内置黑白效果更可控，高光区域默认附带辉光。', ['风格化', '黑白']),
      item('BCC+ Night Vision', '默认是绿色夜视效果，修改颜色和杂色后也可制作雪花屏。', ['风格化', '故障']),
      item('BCC+ X-Ray', '快速生成射线与反相质感。', ['风格化', '射线']),
      item('BCC Bump Map', '根据亮度信息生成凹凸与浮雕，越亮的区域越突出。', ['风格化', '凹凸']),
      item('BCC Cartoon Look', '卡通化处理，可调参数比 AE 内置卡通更多。', ['风格化', '卡通']),
      item('BCC Cartooner', '卡通描边效果，适合快速测试边缘风格。', ['风格化', '描边']),
      item('BCC Charcoal Sketch', '生成炭笔质感的轮廓与描边。', ['风格化', '描边']),
      item('BCC Halftone', '将图像转换成点状半色调效果。', ['风格化', '点阵']),
      item('BCC Median', '通过中值滤波模糊并合并相邻像素边缘。', ['风格化', '模糊']),
      item('BCC Pencil Sketch', '生成比炭笔更清楚锐利的铅笔描边。', ['风格化', '描边']),
      item('BCC Tile Mosaic', '生成规则的瓷砖马赛克效果。', ['风格化', '马赛克']),
      item('BCC Water Color', '快速生成水彩画面质感。', ['风格化', '绘画']),
      item('BCC+ Channel Blur', '可分别控制红、绿、蓝通道模糊，也可直接制作色散模糊。', ['风格化', '色差']),
      item('BCC+ Detail', '根据亮度信息生成近似法线贴图的细节层。', ['风格化', '细节']),
      item('BCC+ Radial Exposure', '径向曝光工具，可以制作暗角或亮角。', ['镜头', '曝光']),
    ],
  },
  {
    id: 'psoft',
    platform: 'ae',
    label: 'PSOFT 系列',
    english: 'PSOFT EFFECTS',
    short: 'PSOFT',
    tone: 'teal',
    source: 'https://app.notion.com/p/AE-PSOFT-3d2b7a683ee780abbfaeccade4f93f9a?pvs=25',
    entries: [
      item('Anti-aliasing', '处理画面边缘锯齿。', ['画质', '边缘']),
      item('P_BlurCel', '选取指定颜色并进行模糊。', ['模糊', '颜色']),
      item('P_BlurCelLayer', '根据参考图层的颜色范围进行模糊。', ['模糊', '图层']),
      item('P_BlurCelMulti', '一个总控加四个分控，可合并多组颜色模糊参数。', ['模糊', '颜色']),
      item('P_BlurCelRadial', '带颜色选择能力的径向模糊。', ['模糊', '径向']),
      item('P_BlurPath', '根据蒙版路径绘制模糊方向。', ['模糊', '路径']),
      item('P_BlurRGB', '分别控制红、绿、蓝通道模糊。', ['模糊', 'RGB']),
      item('P_BoundaryLine', '取色后附加边界描线，适合风格化处理。', ['描边', '取色']),
      item('P_ChromaticAberrations', '提供精细的径向色差控制。', ['色差', '镜头']),
      item('P_ColorSelection', '选取指定颜色并提取遮罩。', ['颜色', '遮罩']),
      item('P_Deband', '提取描边信息，并控制轮廓之外的画面模糊。', ['描边', '模糊']),
      item('P_DeltaFX', '用于缝隙填充与渐变处理。', ['填充', '渐变']),
      item('P_Extend', '取色形成遮罩并向外扩展，接近颜色提取与阻塞组合。', ['颜色', '扩展']),
      item('P_Fill', '填充、叠加模式与透明度三合一。', ['填充', '颜色']),
      item('P_FocusLines', '快速生成聚焦线与速度线。', ['线条', '动势']),
      item('P_Glow', '根据亮度或透明度信息生成发光。', ['发光', '亮度']),
      item('P_Gradient', '创建可控颜色渐变。', ['颜色', '渐变']),
      item('P_GradientMap', '将两种指定颜色映射到画面。', ['颜色', '映射']),
      item('P_Halftone', '按画面信息生成点阵，可用于贴图驱动的粒子变化。', ['点阵', '风格化']),
      item('P_InnerShadow', '选色并生成内部阴影。', ['阴影', '颜色']),
      item('P_PathStroke', '参数更完整的蒙版路径描边。', ['描边', '路径']),
      item('P_Pencil+ 4 Line', '生成四方向铅笔线条风格。', ['描边', '铅笔']),
      item('P_ReplaceColor', '替换画面中的指定颜色。', ['颜色', '替换']),
      item('P_SpeedLines', '生成二维风格速度线。', ['线条', '动势']),
      item('P_Texture', '取色形成遮罩，再向遮罩内阵列填充纹理图层。', ['纹理', '阵列']),
    ],
  },
  {
    id: 'visual',
    platform: 'ae',
    label: '画面效果类',
    english: 'IMAGE EFFECTS',
    short: 'FX',
    tone: 'coral',
    source: 'https://app.notion.com/p/AE-3d2b7a683ee7804c9779ef18585f5763?pvs=25',
    entries: [
      item('Pixel Sorter 3', '像素排序故障效果，常见于游戏 PV 视觉包装。', ['像素', '故障']),
      item('Pixel Melt', '生成像素融化与拖拽效果。', ['像素', '故障']),
      item('RetroDither', '生成 8bit 像素风格，也包含其他抖动模式。', ['像素', '复古']),
      item('Stipple', '将画面转换为点阵排列与粒子聚合效果。', ['粒子', '点阵']),
      item("Crate's Godrays", '生成支持三维空间感的丁达尔光。', ['光线', '空间']),
      item('Fast Bokeh', '使用深度图快速制作景深模糊。', ['景深', '模糊']),
      item('Mojo II', 'Looks 系列调色效果，适合快速建立画面色调。', ['调色', 'Look']),
      item('S_AutoPaint', '生成绘画和伪手绘风格。', ['绘画', '风格化']),
      item('Shadow Studio', '为二维素材或三维平面创建真实投影。', ['阴影', '空间']),
      item('Tracery', '利用颜色追踪生成特效文字框与文字。', ['追踪', '文字']),
      item('Particle Projection', '根据颜色信息控制粒子的运动方向。', ['粒子', '映射']),
      item('Xcloner', '按不同顺序阵列自定义图层，建议通过独立纯色层调用。', ['阵列', '克隆']),
      item('Ballpoint', '生成圆珠笔风格描边，使用时需关闭项目 GPU 加速。', ['描边', '兼容性']),
      item('Vectory', '将画面风格化为线条，需要关闭项目 GPU 加速。', ['线条', '兼容性']),
      item('Dust Transition', '生成画面粒子消散转场，需要关闭项目 GPU 加速。', ['粒子', '转场']),
      item('Motion Mosh', '动态像素拉伸、色差与故障处理。', ['像素', '故障']),
      item('Pixel Encoder', '根据像素识别生成动画。', ['像素', '动画']),
      item('Pixel Galactic', '生成色差、像素和磨砂玻璃混合效果。', ['像素', '色差']),
      item('CRTX', '参数完整的复古电视与故障效果，内置多组模板。', ['复古', '故障']),
      item('RXXR', '批量生成形状和字符像素，适合平面排版。', ['字符', '像素']),
      item('Heat Distortion', '模拟火焰、声浪等造成的空间热扭曲。', ['扭曲', '热浪']),
      item('JPEG Glitch', '生成 JPEG 损坏、花屏和压缩故障。', ['故障', '压缩']),
      item('MaskMotion', '把图层蒙版集中到效果面板，快速调整位移、缩放与旋转。', ['蒙版', '效率']),
      item('Foldspace', '生成三维曲面弯曲动画。', ['三维', '弯曲']),
      item('PathBlurFX', '按照蒙版路径方向进行模糊。', ['路径', '模糊']),
      item('ALStroke 2', '用于创建与控制图形描边。', ['描边', '线条']),
      item('QCA', '生成色彩分离与色差。', ['色差', '颜色']),
      item('ProductionCrate Plugins', '面向特效制作的插件合集。', ['合集', '特效']),
    ],
  },
  {
    id: 'material',
    platform: 'ae',
    label: '素材制作类',
    english: 'ASSET MAKING',
    short: 'MAKE',
    tone: 'blue',
    source: 'https://app.notion.com/p/AE-3d3b7a683ee780739600c7dd22be3a2e?pvs=25',
    entries: [
      item('Power Droste', '生成螺旋递归循环画面，可用于角色 PV 视觉段落。', ['循环', '递归']),
      item('Nebulosity', '一键生成体积雾与云层，并支持摄像机。', ['体积雾', '三维']),
      item('Furikake', '轻量级粒子工具，加载速度明显快于 Particular。', ['粒子', '轻量']),
      item('drAEw', '在 After Effects 中进行逐帧绘画。', ['逐帧', '绘画']),
      item('Fractal Noise 3D', '生成支持三维摄像机的云海与体积效果。', ['云层', '三维']),
    ],
  },
  {
    id: 'builtin',
    platform: 'ae',
    label: 'AE 内置效果',
    english: 'NATIVE EFFECTS',
    short: 'AE',
    tone: 'violet',
    source: 'https://app.notion.com/p/AE-3d3b7a683ee78095aa65d139c9b8ff17?pvs=25',
    entries: [
      item('CC Particle World', '制作粒子发射或激光炮，并能与三维摄像机交互。', ['粒子', '三维']),
      item('CC Page Turn', '快速生成纸张翻页效果。', ['转场', '纸张']),
      item('色光', '常与色阶、线性颜色键组合，用画面颜色提取蒙版。', ['颜色', '遮罩']),
      item('CC Block Load', '生成像素块加载动画。', ['像素', '动画']),
      item('CC Flo Motion', '创建双控制点的吸引、喷出和流动扭曲。', ['扭曲', '流动']),
      item('CC Mr. Mercury', '把图层转化为水、火焰或粘稠液体喷出效果。', ['液体', '粒子']),
      item('CC Mr. Smoothie', '取两个颜色点，将图层颜色重新映射到取样色。', ['颜色', '映射']),
      item('CC Smear', '用两个控制点完成扭曲、拉伸和膨胀，也可制作掀开效果。', ['扭曲', '表达式']),
      item('CC Slant', '进行倾斜和斜切扭曲，也可制作二维素材的伪三维阴影。', ['倾斜', '阴影']),
    ],
  },
  {
    id: 'scripts',
    platform: 'ae',
    label: 'AE 脚本类',
    english: 'AUTOMATION',
    short: 'SCRIPT',
    tone: 'paper',
    source: 'https://app.notion.com/p/AE-3d2b7a683ee780a7bd3ac376d378c2d0?pvs=25',
    entries: [
      item('Soft Body', '设置刚体与受体，接触时自动产生柔体形变，减少手动关键帧。', ['物理', '动画']),
      item('Motion 4.3.1', '包含大量常用动效和效率功能的工具集合。', ['合集', '效率']),
      item('AutoSway', '自动生成风吹摇摆动画。', ['摇摆', '自动化']),
      item('CompSettingTool', '批量修改合成参数。', ['合成', '批处理']),
      item('DeepCopy', '深度复制合成及所有嵌套预合成，避免内部素材继续共享。', ['复制', '合成']),
      item('InstantRecipe', '把效果链、关键帧、表达式、遮罩和图层样式保存为 JSON，并迁移到其他工程。', ['预设', '迁移']),
    ],
  },
  {
    id: 'blender-geometry',
    platform: 'blender',
    label: '几何节点',
    english: 'GEOMETRY NODES',
    short: 'GN',
    tone: 'violet',
    source: blenderHome,
    entries: [
      item('相加', '将两个输入值相加；开启钳制后，会把结果限制在 0 到 1 之间。', ['运算', '钳制'], ['blender/01-add.png']),
      item('相减', '用第一个输入值减去第二个输入值，也可以配合区间翻转做反向控制。', ['运算', '区间'], ['blender/02-subtract.png']),
      item('相乘', '将两个输入值相乘；开启钳制后，会把结果限制在 0 到 1 之间。', ['运算', '钳制'], ['blender/03-multiply.png']),
      item('相除', '用第一个输入值除以第二个输入值，适合建立比例和归一化关系。', ['运算', '比例'], ['blender/04-divide.png']),
      item('正弦', '按正弦曲线输出循环波段，可用 pi、2pi 和常用角度控制重复节奏。', ['波形', '循环'], ['blender/05-sine.png']),
      item('余弦', '按余弦曲线输出循环波段；切换成正弦时，可在前方减去 pi / 2。', ['波形', '循环'], ['blender/06-cosine.png', 'blender/06-cosine-chart.jpg']),
      item('重复', '几何数据经过效果区和输出点后回到接入点，形成可控的迭代结构。', ['迭代', '结构'], ['blender/07-repeat.png', 'blender/07-repeat-example.png']),
    ],
  },
]

export const allEntries = categories.flatMap((category) =>
  category.entries.map((entry, index) => ({
    ...entry,
    id: `${category.id}-${index + 1}`,
    number: String(index + 1).padStart(2, '0'),
    categoryId: category.id,
    category: category.label,
    categoryEnglish: category.english,
    platform: category.platform,
    tone: category.tone,
    source: category.source,
  })),
)
